In [1]:
!pip install -q google-genai

In [2]:
from google.colab import userdata
from google import genai

api_key = userdata.get("GEMINI_API_KEY")

client = genai.Client(api_key=api_key)

print("Gemini client initialized successfully.")

Gemini client initialized successfully.

In [4]:
response = client.models.generate_content(
    model="gemini-3.6-flash",
    contents="Reply with exactly: Gemini is working."
)

print(response.text)

Gemini is working.

In [5]:
!pip install -q feedparser

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.7/80.7 kB 4.0 MB/s eta 0:00:00

In [6]:
import feedparser
from urllib.parse import quote
import pandas as pd

In [7]:
def get_google_news(query, language="id", country="ID"):
    encoded_query = quote(query)

    url = (
        f"https://news.google.com/rss/search?"
        f"q={encoded_query}&hl={language}&gl={country}&ceid={country}:{language}"
    )

    feed = feedparser.parse(url)

    articles = []

    for entry in feed.entries:
        articles.append({
            "title": entry.get("title", ""),
            "url": entry.get("link", ""),
            "published": entry.get("published", ""),
            "summary": entry.get("summary", "")
        })

    return articles

In [8]:
articles = get_google_news("properti Indonesia")

print(f"Retrieved {len(articles)} articles")

for article in articles[:5]:
    print("\nTITLE:", article["title"])
    print("DATE:", article["published"])
    print("URL:", article["url"])

Retrieved 100 articles

TITLE: Taipan Properti Divonis Penjara Seumur Hidup, Ini Kasusnya - CNBC Indonesia
DATE: Thu, 20 Aug 2026 08:20:00 GMT
URL: https://news.google.com/rss/articles/CBMitwFBVV95cUxQM0FyODlIRWhkYkwtZjJrZXdhaUZaWVRFSkJYQmtuVG9mNF94RE9xVzZBR3dXeXhQZ2ZiTjY4X05qLUs3bF9kLTlzRmhiY2JHbkRnT1hzQkdFTUg3ZzJoYzVEc0cyY3FoR25wRjlDN0NwYzZqQjVmcHh5bzBERFRjTnh1a2s0M0VhX29UdXZvQXdLZm1OLWE2eTRDNzVKWXA1dEJISDZfRnNZNWhZMURzVWJCMHd1RWfSAbwBQVVfeXFMTTJfb1VobXhvT0hZYXE2ZzVIaWZ3TG5xd09CU1h0ZzJLOFRjQ2dPVFF1T011VzNFNDVRM2ktNC02QnFhcnhMeF9zSlRyeGNVWG1CNGY5QW92NTVaNXp3QTYtNExhdjA1bzRFRjVzYUhtVlV6blRPTFByRXY3X1dsWXMxVUVQYlVINS1LSEw5LUFTX0hCNm96QU9ZdmtWVmZVaXhDdTZzd1Vjc0pxRzJnUmhpRFJfYzN4WWxEZzY?oc=5

TITLE: Pos Properti Pajang Produk Hunian di Danantara Housing Expo 2026 - achmadnurhidayat.id
DATE: Thu, 20 Aug 2026 01:49:23 GMT
URL: https://news.google.com/rss/articles/CBMigwFBVV95cUxPS1ZRdXBhQmE5YVZELUlSUHRuamx3N2lsVDZhbnNHWGZvOWE3aFRmUkYtS3hlRmxLY3p5clB0aDNHZk1FS0tvV0R1dHQzRC1mcl95RFV1SnZfd1htMjB3NTBIdmpMekNRNlFYWDF6QjQwYkJGeXhYNmY3WEV0UDlMUWNhOA?oc=5

TITLE: Pos Properti Hadir di Danantara Housing Expo - investor.id
DATE: Thu, 20 Aug 2026 01:32:11 GMT
URL: https://news.google.com/rss/articles/CBMihwFBVV95cUxPSTVxanJoMHBRMl9MRWpSbkxuaWswNDFqUHBuY2lCejRSUS1xT0NEZ0R2N0J0VEROcHNuRkZWampqME9McjRuOGVQWjZ2VEFrMVFFR2RGNE12OHBtVlQ2eWlzZWpFc3RvX0cxUllZbWtCX2xPeHR0UlVidnN6V1MtQ1YyWkZBSlE?oc=5

TITLE: Arah Saham Properti Usai Kehadiran PFII - Market - Bloomberg Technoz
DATE: Tue, 18 Aug 2026 07:56:26 GMT
URL: https://news.google.com/rss/articles/CBMilgFBVV95cUxOUWVSU3RmZFhicWJldG5YeFpwT0FqNFpkWmRJTnI4ZWRPUHFFNEkzMklFN1I2RHQ5dGRhWm5DeFltTmhpUklsLXdvWWhBMXpKenhQY21STm94UG1KYUlmLU1qck9tX1NsajUxYzhQWVJJN1l6V1Q5VkZNVTlZbWt5SmlRRXBBQWcwcW5zX1NpTDlOZFF4TXc?oc=5

TITLE: Kontribusi Pajak dari Sektor Properti Indonesia Berkurang Selama 2015-2024 - Databoks Katadata
DATE: Wed, 12 Aug 2026 07:00:00 GMT
URL: https://news.google.com/rss/articles/CBMi1gFBVV95cUxONFMzWTl5RzhMOGRlNkFUUFViMHBUTS1TWGp6Vm9TUlF3cUh5TlhRYmMxZWZvcE0xTUxTTXNNandhdjdPODVhaDVyZmVxRTVuMTY5cV9UNGpuVlFHWm5FWEVoZXpZWlM0REN2N21ybkJqdDRQR2szWV9FNXhVOUxTaHViX1NLeFZXLXNIb0pvVHFfNlY2YVNYOEJ2eDY2N21KcUtuQjBySEZVbTM5N1VRWm96MkRadlUzd1pqOFRpb2VWZXdZODlNdFRPOGtIMWhfR1Y2Nk1B?oc=5

In [9]:
df = pd.DataFrame(articles)

df.head()

,title,url,published,summary
0,"Taipan Properti Divonis Penjara Seumur Hidup, ...",https://news.google.com/rss/articles/CBMitwFBV...,"Thu, 20 Aug 2026 08:20:00 GMT","<a href=""https://news.google.com/rss/articles/..."
1,Pos Properti Pajang Produk Hunian di Danantara...,https://news.google.com/rss/articles/CBMigwFBV...,"Thu, 20 Aug 2026 01:49:23 GMT","<a href=""https://news.google.com/rss/articles/..."
2,Pos Properti Hadir di Danantara Housing Expo -...,https://news.google.com/rss/articles/CBMihwFBV...,"Thu, 20 Aug 2026 01:32:11 GMT","<a href=""https://news.google.com/rss/articles/..."
3,Arah Saham Properti Usai Kehadiran PFII - Mark...,https://news.google.com/rss/articles/CBMilgFBV...,"Tue, 18 Aug 2026 07:56:26 GMT","<a href=""https://news.google.com/rss/articles/..."
4,Kontribusi Pajak dari Sektor Properti Indonesi...,https://news.google.com/rss/articles/CBMi1gFBV...,"Wed, 12 Aug 2026 07:00:00 GMT","<a href=""https://news.google.com/rss/articles/..."

In [10]:
queries = [
    "properti Indonesia",
    "KPR Indonesia",
    "harga rumah Indonesia",
    "suku bunga KPR",
    "pasar properti Indonesia"
]

all_articles = []

for query in queries:
    results = get_google_news(query)

    for article in results:
        article["query"] = query
        all_articles.append(article)

news_df = pd.DataFrame(all_articles)

print(f"Total articles retrieved: {len(news_df)}")

Total articles retrieved: 500

In [11]:
news_df.head()

,title,url,published,summary,query
0,"Taipan Properti Divonis Penjara Seumur Hidup, ...",https://news.google.com/rss/articles/CBMitwFBV...,"Thu, 20 Aug 2026 08:20:00 GMT","<a href=""https://news.google.com/rss/articles/...",properti Indonesia
1,Pos Properti Pajang Produk Hunian di Danantara...,https://news.google.com/rss/articles/CBMigwFBV...,"Thu, 20 Aug 2026 01:49:23 GMT","<a href=""https://news.google.com/rss/articles/...",properti Indonesia
2,Pos Properti Hadir di Danantara Housing Expo -...,https://news.google.com/rss/articles/CBMihwFBV...,"Thu, 20 Aug 2026 01:32:11 GMT","<a href=""https://news.google.com/rss/articles/...",properti Indonesia
3,Arah Saham Properti Usai Kehadiran PFII - Mark...,https://news.google.com/rss/articles/CBMilgFBV...,"Tue, 18 Aug 2026 07:56:26 GMT","<a href=""https://news.google.com/rss/articles/...",properti Indonesia
4,Kontribusi Pajak dari Sektor Properti Indonesi...,https://news.google.com/rss/articles/CBMi1gFBV...,"Wed, 12 Aug 2026 07:00:00 GMT","<a href=""https://news.google.com/rss/articles/...",properti Indonesia

In [12]:
news_df = news_df.drop_duplicates(subset="url")

print(f"After removing duplicates: {len(news_df)}")

After removing duplicates: 456

In [13]:
news_df[["title", "published", "query"]].head(20)

,title,published,query
0,"Taipan Properti Divonis Penjara Seumur Hidup, ...","Thu, 20 Aug 2026 08:20:00 GMT",properti Indonesia
1,Pos Properti Pajang Produk Hunian di Danantara...,"Thu, 20 Aug 2026 01:49:23 GMT",properti Indonesia
2,Pos Properti Hadir di Danantara Housing Expo -...,"Thu, 20 Aug 2026 01:32:11 GMT",properti Indonesia
3,Arah Saham Properti Usai Kehadiran PFII - Mark...,"Tue, 18 Aug 2026 07:56:26 GMT",properti Indonesia
4,Kontribusi Pajak dari Sektor Properti Indonesi...,"Wed, 12 Aug 2026 07:00:00 GMT",properti Indonesia
5,Kemitraan Moladin Finance dan Pashouses Hadirk...,"Wed, 19 Aug 2026 13:05:00 GMT",properti Indonesia
6,PT Pos Properti Indonesia Perkuat Adaptive GRC...,"Fri, 14 Aug 2026 09:14:00 GMT",properti Indonesia
7,[HOAKS] Link Daftar Kerja Pos Properti Indones...,"Sun, 09 Aug 2026 00:15:00 GMT",properti Indonesia
8,Kementerian Komunikasi dan Digital - Kementeri...,"Wed, 05 Aug 2026 07:00:00 GMT",properti Indonesia
9,"Pemulihan Properti Jakarta 2026 Kian Nyata, In...","Tue, 18 Aug 2026 12:51:00 GMT",properti Indonesia
10,IMREI Perkuat Kolaborasi dengan AREA Indonesia...,"Mon, 27 Jul 2026 07:00:00 GMT",properti Indonesia
11,[PENIPUAN] Foto Pendaftaran Lowongan Kerja Pos...,"Tue, 04 Aug 2026 07:00:00 GMT",properti Indonesia
12,Update 56 Saham HSC BEI per 18 Agustus 2026: M...,"Tue, 18 Aug 2026 04:48:41 GMT",properti Indonesia
13,Rumah123 dan IPW Gelar The People’s Choice 202...,"Wed, 19 Aug 2026 08:52:10 GMT",properti Indonesia
14,"Ray White Indonesia Raih Top Brand Award 2026,...","Wed, 12 Aug 2026 11:33:41 GMT",properti Indonesia
15,Pajak Properti Indonesia Stagnan 15 Tahun Mesk...,"Fri, 03 Jul 2026 07:00:00 GMT",properti Indonesia
16,"Lixil Perkuat Ekosistem Arsitektur, Dorong Ino...","Mon, 03 Aug 2026 19:58:00 GMT",properti Indonesia
17,The People's Choice 2026: 427 Ribu Suara Konsu...,"Wed, 12 Aug 2026 05:57:23 GMT",properti Indonesia
18,APLN dan Hankyu Hanshin Perkuat Kemitraan Stra...,"Mon, 10 Aug 2026 12:07:04 GMT",properti Indonesia
19,Pos Properti: Aset PosIND yang Menghasilkan Ni...,"Thu, 18 Jun 2026 19:45:19 GMT",properti Indonesia

In [14]:
!pip install -q beautifulsoup4

In [15]:
from bs4 import BeautifulSoup

def clean_html(text):
    return BeautifulSoup(text, "html.parser").get_text(" ", strip=True)

news_df["summary"] = news_df["summary"].apply(clean_html)

news_df.head()

,title,url,published,summary,query
0,"Taipan Properti Divonis Penjara Seumur Hidup, ...",https://news.google.com/rss/articles/CBMitwFBV...,"Thu, 20 Aug 2026 08:20:00 GMT","Taipan Properti Divonis Penjara Seumur Hidup, ...",properti Indonesia
1,Pos Properti Pajang Produk Hunian di Danantara...,https://news.google.com/rss/articles/CBMigwFBV...,"Thu, 20 Aug 2026 01:49:23 GMT",Pos Properti Pajang Produk Hunian di Danantara...,properti Indonesia
2,Pos Properti Hadir di Danantara Housing Expo -...,https://news.google.com/rss/articles/CBMihwFBV...,"Thu, 20 Aug 2026 01:32:11 GMT",Pos Properti Hadir di Danantara Housing Expo i...,properti Indonesia
3,Arah Saham Properti Usai Kehadiran PFII - Mark...,https://news.google.com/rss/articles/CBMilgFBV...,"Tue, 18 Aug 2026 07:56:26 GMT",Arah Saham Properti Usai Kehadiran PFII - Mark...,properti Indonesia
4,Kontribusi Pajak dari Sektor Properti Indonesi...,https://news.google.com/rss/articles/CBMi1gFBV...,"Wed, 12 Aug 2026 07:00:00 GMT",Kontribusi Pajak dari Sektor Properti Indonesi...,properti Indonesia

In [16]:
news_df["published_dt"] = pd.to_datetime(
    news_df["published"],
    errors="coerce",
    utc=True
)

news_df = news_df.sort_values(
    "published_dt",
    ascending=False
)

candidate_df = news_df.head(20).copy()

print(f"Sending {len(candidate_df)} articles to Gemini")

Sending 20 articles to Gemini

In [17]:
candidate_df[["title", "published", "query"]]

,title,published,query
310,Video Korsel Beri Paket KPR Murah untuk Anak M...,"Thu, 20 Aug 2026 10:54:33 GMT",suku bunga KPR
301,BCA Expo Surabaya 2026 Jadi Pembuka Semester I...,"Thu, 20 Aug 2026 09:53:00 GMT",suku bunga KPR
303,"Digelar di Tujuh Kota, BCA Expo 2026 Tebar Bun...","Thu, 20 Aug 2026 09:27:00 GMT",suku bunga KPR
0,"Taipan Properti Divonis Penjara Seumur Hidup, ...","Thu, 20 Aug 2026 08:20:00 GMT",properti Indonesia
313,"BCA Expo 2026 Digelar di 7 Kota, Ada Promo KPR...","Thu, 20 Aug 2026 05:21:00 GMT",suku bunga KPR
1,Pos Properti Pajang Produk Hunian di Danantara...,"Thu, 20 Aug 2026 01:49:23 GMT",properti Indonesia
2,Pos Properti Hadir di Danantara Housing Expo -...,"Thu, 20 Aug 2026 01:32:11 GMT",properti Indonesia
344,"BCA Expo 2026 Hadir di 7 Kota: Cek Jadwal, Bun...","Wed, 19 Aug 2026 13:52:00 GMT",suku bunga KPR
391,"BBCA Gelar Expo, Diharapkan Pacu Kredit Konsum...","Wed, 19 Aug 2026 13:52:00 GMT",suku bunga KPR
5,Kemitraan Moladin Finance dan Pashouses Hadirk...,"Wed, 19 Aug 2026 13:05:00 GMT",properti Indonesia
326,"KPR BCA Kuasai 21,3 Persen Pasar, Apa Strategi...","Wed, 19 Aug 2026 12:52:00 GMT",suku bunga KPR
300,"Suku bunga KPR stabil di 6,77%, permintaan bel...","Wed, 19 Aug 2026 11:55:47 GMT",suku bunga KPR
307,"BCA Catat Penjualan Properti Naik 30%, KPR Mas...","Wed, 19 Aug 2026 10:18:00 GMT",suku bunga KPR
387,BCA pacu kredit konsumsi lewat BCA Expo 2026 -...,"Wed, 19 Aug 2026 09:48:42 GMT",suku bunga KPR
358,"BCA Expo 2026, Tawarkan Bunga Spesial KPR dan ...","Wed, 19 Aug 2026 09:09:26 GMT",suku bunga KPR
103,"BI Rate Tetap 5,75 Persen, Apa Dampaknya bagi ...","Wed, 19 Aug 2026 09:08:00 GMT",KPR Indonesia
13,Rumah123 dan IPW Gelar The People’s Choice 202...,"Wed, 19 Aug 2026 08:52:10 GMT",properti Indonesia
401,Pasar Properti Jakarta Tunjukkan Perkembangan ...,"Wed, 19 Aug 2026 08:05:00 GMT",pasar properti Indonesia
400,Logistik dan Data Center Jadi Motor Pertumbuha...,"Wed, 19 Aug 2026 08:01:54 GMT",pasar properti Indonesia
202,Ini Negara dengan Harga Rumah Paling Terjangka...,"Wed, 19 Aug 2026 06:08:00 GMT",harga rumah Indonesia

In [22]:
selection_prompt = """
You are the editorial selection engine for an Indonesian
property marketplace.

The target audience is Indonesian young adults aged 22–28,
especially people who are beginning to earn their own income
and may eventually rent or buy a home.

Below is a list of recent news articles.

Your task is to select the TOP 5 articles that have the
highest potential for an educational Instagram post.

Evaluate each article based on:

1. Relevance to Indonesian property and housing
2. Geographic relevance to Indonesia
3. Practical usefulness to young adults
4. Financial or policy implications
5. Presence of concrete facts, numbers, or developments
6. Timeliness
7. Potential to explain the topic clearly in an Instagram carousel

Avoid or heavily penalize:

- Hoaxes or misinformation
- Job scams
- Pure corporate announcements
- Promotional advertisements
- Company marketing content
- Celebrity/gossip stories
- News unrelated to housing or property
- Stories with little educational value

Important:
Do not invent information.
Base your evaluation only on the information provided.

Geographic rule:
Prioritize news directly concerning Indonesia.

International news should normally be excluded unless it provides
a highly useful comparison, benchmark, or lesson that can be
directly connected to Indonesian housing consumers.

Return ONLY valid JSON in this format:

{
  "ranked_articles": [
    {
      "rank": 1,
      "article_index": 0,
      "title": "...",
      "score": 0,
      "topic": "...",
      "reason": "..."
    }
  ]
}

Return exactly 5 articles, ranked from best to worst.
"""

In [23]:
articles_for_ai = []

for index, row in candidate_df.iterrows():
    articles_for_ai.append({
        "index": int(index),
        "title": row["title"],
        "published": row["published"],
        "summary": row["summary"],
        "url": row["url"]
    })

articles_text = "\n\n".join(
    [
        f"""
ARTICLE INDEX: {article['index']}
TITLE: {article['title']}
PUBLISHED: {article['published']}
SUMMARY: {article['summary']}
URL: {article['url']}
"""
        for article in articles_for_ai
    ]
)

In [24]:
response = client.models.generate_content(
    model="gemini-3.6-flash",
    contents=selection_prompt + "\n\n" + articles_text
)

print(response.text)

```json
{
  "ranked_articles": [
    {
      "rank": 1,
      "article_index": 300,
      "title": "Suku bunga KPR stabil di 6,77%, permintaan beli dan refinancing rumah melambat. - Pluang",
      "score": 92,
      "topic": "Tren Suku Bunga KPR dan Dinamika Pasar",
      "reason": "Sangat relevan secara finansial untuk anak muda berusia 22–28 tahun yang merencanakan KPR. Artikel ini memuat data konkret (suku bunga 6,77%) serta menjelaskan tren pembelian dan refinancing rumah secara objektif tanpa muatan promosi merek."
    },
    {
      "rank": 2,
      "article_index": 103,
      "title": "BI Rate Tetap 5,75 Persen, Apa Dampaknya bagi Kredit, KPR, dan Deposito? - mediata.id",
      "score": 88,
      "topic": "Dampak Kebijakan BI Rate terhadap KPR",
      "reason": "Memberikan edukasi finansial makro yang krusial mengenai penahanan BI Rate di level 5,75% dan implikasi langsungnya terhadap bunga KPR. Sangat cocok dijadikan materi carousel Instagram untuk meningkatkan literasi keuangan calon pembeli rumah pertama."
    },
    {
      "rank": 3,
      "article_index": 202,
      "title": "Ini Negara dengan Harga Rumah Paling Terjangkau di Asia Tenggara - Databoks Katadata",
      "score": 82,
      "topic": "Keterjangkauan Harga Rumah di Asia Tenggara",
      "reason": "Menyajikan data komparatif mengenai keterjangkauan hunian di Indonesia dibandingkan negara tetangga di Asia Tenggara. Sangat edukatif dan berpotensi memicu diskusi interaktif di media sosial mengenai realitas harga properti."
    },
    {
      "rank": 4,
      "article_index": 401,
      "title": "Pasar Properti Jakarta Tunjukkan Perkembangan Positif di Kuartal Kedua 2026 - olenka.id",
      "score": 78,
      "topic": "Perkembangan Pasar Properti Jakarta Kuartal II 2026",
      "reason": "Memberikan gambaran kondisi pasar properti terkini di pusat ekonomi utama (Jakarta). Berisi fakta perkembangan pasar kuartalan yang berguna bagi pekerja muda yang mempertimbangkan hunian di area perkotaan."
    },
    {
      "rank": 5,
      "article_index": 310,
      "title": "Video Korsel Beri Paket KPR Murah untuk Anak Muda & Pengantin Baru - 20detik",
      "score": 72,
      "topic": "Studi Komparasi Kebijakan KPR Murah untuk Pasangan Muda",
      "reason": "Meskipun berfokus pada berita internasional, artikel ini menyajikan ide kebijakan yang sangat relevan sebagai tolok ukur/pembanding bagi konsumen anak muda dan pasangan baru di Indonesia dalam memahami opsi skema KPR khusus pemuda."
    }
  ]
}
```

In [27]:
import json
selection_result = json.loads(response.text.strip('```json').strip('```'))
selection_result

{'ranked_articles': [{'rank': 1,
   'article_index': 300,
   'title': 'Suku bunga KPR stabil di 6,77%, permintaan beli dan refinancing rumah melambat. - Pluang',
   'score': 92,
   'topic': 'Tren Suku Bunga KPR dan Dinamika Pasar',
   'reason': 'Sangat relevan secara finansial untuk anak muda berusia 22–28 tahun yang merencanakan KPR. Artikel ini memuat data konkret (suku bunga 6,77%) serta menjelaskan tren pembelian dan refinancing rumah secara objektif tanpa muatan promosi merek.'},
  {'rank': 2,
   'article_index': 103,
   'title': 'BI Rate Tetap 5,75 Persen, Apa Dampaknya bagi Kredit, KPR, dan Deposito? - mediata.id',
   'score': 88,
   'topic': 'Dampak Kebijakan BI Rate terhadap KPR',
   'reason': 'Memberikan edukasi finansial makro yang krusial mengenai penahanan BI Rate di level 5,75% dan implikasi langsungnya terhadap bunga KPR. Sangat cocok dijadikan materi carousel Instagram untuk meningkatkan literasi keuangan calon pembeli rumah pertama.'},
  {'rank': 3,
   'article_index': 202,
   'title': 'Ini Negara dengan Harga Rumah Paling Terjangkau di Asia Tenggara - Databoks Katadata',
   'score': 82,
   'topic': 'Keterjangkauan Harga Rumah di Asia Tenggara',
   'reason': 'Menyajikan data komparatif mengenai keterjangkauan hunian di Indonesia dibandingkan negara tetangga di Asia Tenggara. Sangat edukatif dan berpotensi memicu diskusi interaktif di media sosial mengenai realitas harga properti.'},
  {'rank': 4,
   'article_index': 401,
   'title': 'Pasar Properti Jakarta Tunjukkan Perkembangan Positif di Kuartal Kedua 2026 - olenka.id',
   'score': 78,
   'topic': 'Perkembangan Pasar Properti Jakarta Kuartal II 2026',
   'reason': 'Memberikan gambaran kondisi pasar properti terkini di pusat ekonomi utama (Jakarta). Berisi fakta perkembangan pasar kuartalan yang berguna bagi pekerja muda yang mempertimbangkan hunian di area perkotaan.'},
  {'rank': 5,
   'article_index': 310,
   'title': 'Video Korsel Beri Paket KPR Murah untuk Anak Muda & Pengantin Baru - 20detik',
   'score': 72,
   'topic': 'Studi Komparasi Kebijakan KPR Murah untuk Pasangan Muda',
   'reason': 'Meskipun berfokus pada berita internasional, artikel ini menyajikan ide kebijakan yang sangat relevan sebagai tolok ukur/pembanding bagi konsumen anak muda dan pasangan baru di Indonesia dalam memahami opsi skema KPR khusus pemuda.'}]}

In [28]:
winner_index = selection_result["ranked_articles"][0]["article_index"]

winner = candidate_df.loc[winner_index]

print("Selected article:")
print(winner["title"])
print(winner["url"])

Selected article:
Suku bunga KPR stabil di 6,77%, permintaan beli dan refinancing rumah melambat. - Pluang
https://news.google.com/rss/articles/CBMijgFBVV95cUxPdTJveTlkNktCcG5aXzM4TjlUYWJNQ0pzZTBLdVZGanNpYWRRVTFlTkg1UTRQUWZwVFBaR25NV3RhaHRadFFFUnRLOGl3c25YZVM4V2VFVnpheXFZSzJzczdmUnBTWFc3SUtaZlRRMGRONUdyT3R0N3hSUXlEc19sQUtOMDRnb1I2UU5aeUF3?oc=5

In [29]:
generation_prompt = """
You are a social media content strategist for an Indonesian
online property marketplace.

Your target audience is Indonesian Gen Z and young millennials,
approximately 22–28 years old, who are beginning to manage
their own finances and may be considering renting or buying
their first home.

Using ONLY the supplied news article, create an educational
Instagram carousel about the story.

The goal is not simply to summarize the article.
The goal is to explain why the development matters to a young
Indonesian who may eventually buy a home or take a KPR.

Create exactly 7 slides:

Slide 1:
A strong hook that makes the audience want to keep reading.

Slide 2:
Explain what happened in simple language.

Slide 3:
Explain the most important number, statistic, or development.

Slide 4:
Explain why this matters for the property market.

Slide 5:
Explain what this could mean for a young prospective
homebuyer.

Slide 6:
Give a practical financial takeaway.
Do not give personalized financial advice.

Slide 7:
Give a concise takeaway and engaging CTA.

Tone:
- conversational
- intelligent
- accessible
- slightly playful
- appropriate for Indonesian Gen Z
- not overly corporate
- not excessively slang-heavy

IMPORTANT FACTUAL RULES:
- Do not invent statistics.
- Do not invent quotes.
- Do not invent dates.
- Do not invent financial advice or claims.
- Every factual claim must be supported by the supplied article.
- Clearly distinguish between facts from the article and general
  financial guidance.
- If the article does not provide enough information to support
  a claim, do not make that claim.

Also create:
1. An Instagram caption of approximately 100–150 words.
2. A short CTA.
3. Source attribution.

Return ONLY valid JSON in this format:

{
  "carousel": [
    {
      "slide": 1,
      "headline": "...",
      "body": "..."
    }
  ],
  "caption": "...",
  "cta": "...",
  "source": "..."
}
"""

In [30]:
winner_text = f"""
TITLE:
{winner["title"]}

PUBLISHED:
{winner["published"]}

SUMMARY:
{winner["summary"]}

SOURCE:
{winner["url"]}
"""

In [31]:
generation_response = client.models.generate_content(
    model="gemini-3.6-flash",
    contents=generation_prompt + "\n\n" + winner_text
)

print(generation_response.text)

```json
{
  "carousel": [
    {
      "slide": 1,
      "headline": "Bunga KPR Stabil, Tapi Kok Pada Ngerem Beli Rumah?",
      "body": "Suku bunga KPR tercatat stabil di angka 6,77%. Tapi uniknya, tren beli rumah dan refinancing justru lagi melambat. Yuk, kita bedah artinya buat rencana hunian pertama kamu!"
    },
    {
      "slide": 2,
      "headline": "Apa yang Sebenarnya Terjadi?",
      "body": "Berdasarkan data pasar terbaru, tingkat suku bunga KPR berada di posisi stabil. Momen ini diwarnai dengan penurunan kecepatan atau perlambatan pada permintaan pembelian rumah baru serta pengajuan refinancing KPR."
    },
    {
      "slide": 3,
      "headline": "Angka Kuncinya: 6,77%",
      "body": "Angka 6,77% ini adalah posisi suku bunga KPR yang terpantau stabil saat ini. Bunga yang tidak bergerak naik maupun turun ini menjadi acuan utama perbankan dalam menentukan beban cicilan hunian masyarakat."
    },
    {
      "slide": 4,
      "headline": "Dampaknya ke Pasar Properti",
      "body": "Ketika suku bunga stabil tetapi permintaan beli dan refinancing melambat, ini menandakan pasar sedang dalam fase kehati-hatian. Banyak calon pembeli yang memilih untuk wait and see sebelum mengambil keputusan finansial besar."
    },
    {
      "slide": 5,
      "headline": "Artinya Buat Kamu yang Mau Beli Rumah",
      "body": "Pasar yang sedang melambat memberi kamu napas ekstra untuk tidak terburu-buru. Suku bunga yang stabil di 6,77% memudahkan kamu dalam menghitung kepastian estimasi cicilan tanpa khawatir lonjakan bunga mendadak."
    },
    {
      "slide": 6,
      "headline": "Langkah Finansial Cerdas",
      "body": "(Catatan: Ini panduan finansial umum, bukan nasihat pribadi). Momen pasar melambat cocok dipakai untuk merapikan cash flow dan menabung DP. Idealnya, alokasikan total cicilan utang maksimal 30% dari gaji bulananmu."
    },
    {
      "slide": 7,
      "headline": "Siap Rencanakan Rumah Impian?",
      "body": "Bunga KPR stabil 6,77% adalah kesempatan bagus buat makin melek finansial. Pelajari pasarnya, hitung simulasinya, dan ambil langkah saat kamu benar-benar siap secara finansial!"
    }
  ],
  "caption": "Lagi mikir-mikir mau ambil KPR atau tunda dulu? 🏡\n\nKabar terbaru menunjukkan kalau suku bunga KPR saat ini berada di posisi stabil yaitu 6,77%. Uniknya, di tengah suku bunga yang stabil ini, minat masyarakat untuk membeli rumah baru maupun melakukan refinancing KPR justru tercatat mengalami perlambatan.\n\nBuat kamu Gen Z dan millennial yang sedang merencanakan rumah pertama, situasi pasar ini bisa jadi momen pas untuk bernapas sejenak dan merapikan kondisi keuangan. Bunga yang stabil memberikan kepastian lebih saat kamu menyusun simulasi cicilan bulanan.\n\nIngat, pastikan kondisi finansialmu sudah benar-benar siap sebelum berkomitmen pada KPR jangka panjang, ya!\n\nSave postingan ini buat pengingat finansialmu dan share ke teman kamu yang lagi berburu rumah! 💡",
  "cta": "Ketik 'KPR' di kolom komentar kalau kamu mau mulai simulasi cicilan rumah impianmu hari ini!",
  "source": "Pluang (Rabu, 19 Agustus 2026)"
}
```

In [45]:
qa_prompt = """
You are a strict editorial fact-checker for an Indonesian
property marketplace.

Review the generated Instagram carousel and caption against
the original source article.

Your job is NOT to rewrite the content.

Identify:

1. Unsupported factual claims
2. Numbers/statistics that do not appear in the source
3. Claims that incorrectly imply causation
4. Financial advice that is presented as fact
5. Claims that are too certain given the available evidence
6. Statements that could mislead a prospective homebuyer
7. Claims that require additional context or qualification

For every issue, explain:
- the exact problematic statement
- why it is problematic
- severity: LOW, MEDIUM, or HIGH
- suggested correction

A factual claim about the news itself must be supported by the
supplied source.

However, audience framing and editorial language do NOT need to
appear in the source. For example, referring to "young adults",
"Gen Z", or "first-time homebuyers" is acceptable when it is used
to frame the content for the intended audience, as long as it does
not falsely claim that the source specifically studied or reported
on that demographic.

General financial guidance may be included if clearly identified
as general guidance rather than information from the article.

Do not flag a statement merely because it is editorial framing.
Focus on factual accuracy, unsupported causation, misleading
financial claims, invented statistics, and unsupported
specificity.

Do not assume information that is not explicitly provided.
Pay particular attention to financial claims.

Do NOT require every sentence of the Instagram post to be
directly stated in the source. The purpose of the workflow is to
transform news into useful educational content while preserving
factual accuracy.

Return ONLY valid JSON:

{
  "overall_status": "PASS" or "NEEDS_REVISION",
  "issues": [
    {
      "slide": 0,
      "problematic_statement": "...",
      "reason": "...",
      "severity": "LOW",
      "suggested_correction": "..."
    }
  ]
}
"""

In [46]:
generation_result = json.loads(generation_response.text.strip('```json').strip('```'))

In [47]:
qa_input = f"""
ORIGINAL NEWS ARTICLE

Title:
{winner["title"]}

Published:
{winner["published"]}

Summary:
{winner["summary"]}

URL:
{winner["url"]}


GENERATED INSTAGRAM CONTENT

{json.dumps(generation_result, ensure_ascii=False, indent=2)}
"""

In [48]:
qa_response = client.models.generate_content(
    model="gemini-3.6-flash",
    contents=qa_prompt + "\n\n" + qa_input
)

print(qa_response.text)

{
  "overall_status": "NEEDS_REVISION",
  "issues": [
    {
      "slide": 3,
      "problematic_statement": "Bunga yang tidak bergerak naik maupun turun ini menjadi acuan utama perbankan dalam menentukan beban cicilan hunian masyarakat.",
      "reason": "Artikel sumber hanya menyebutkan bahwa suku bunga KPR saat ini stabil di angka 6,77%. Klaim bahwa angka ini merupakan 'acuan utama perbankan' merupakan spesifikasi/klaim faktual yang tidak didukung oleh sumber.",
      "severity": "LOW",
      "suggested_correction": "Angka 6,77% ini mencerminkan rata-rata tingkat suku bunga KPR yang terpantau stabil saat ini."
    },
    {
      "slide": 5,
      "problematic_statement": "Suku bunga yang stabil di 6,77% memudahkan kamu dalam menghitung kepastian estimasi cicilan tanpa khawatir lonjakan bunga mendadak.",
      "reason": "Stabilitas suku bunga pasar saat ini tidak menjamin bahwa skema KPR individu (terutama KPR suku bunga mengambang/floating) bebas dari lonjakan bunga di masa depan. Pernyataan ini terlalu pasti (too certain) dan dapat menyesatkan calon pembeli rumah.",
      "severity": "MEDIUM",
      "suggested_correction": "Suku bunga yang stabil di 6,77% memudahkan kamu dalam merancang estimasi cicilan berdasarkan kondisi pasar saat ini."
    }
  ]
}

In [49]:
revision_prompt = """
You are the final editorial revision engine for an Indonesian
property marketplace.

You have been given:

1. The original news article
2. A draft Instagram carousel and caption
3. A fact-checking report identifying problems

Revise the draft according to the fact-checker's findings.

Requirements:

- Preserve the useful information from the original draft.
- Remove unsupported factual claims.
- Do not invent new statistics, facts, dates, or quotes.
- Do not introduce new information that is not supported by the
  original article.
- Do not present speculation as fact.
- Be especially careful with financial claims.
- Do not imply that a current interest rate guarantees future
  interest rates.
- If general financial guidance is included, clearly distinguish
  it from information contained in the news article.
- Maintain an engaging Indonesian Gen-Z-friendly tone.
- Keep exactly 7 slides.

Return ONLY valid JSON:

{
  "carousel": [
    {
      "slide": 1,
      "headline": "...",
      "body": "..."
    }
  ],
  "caption": "...",
  "cta": "...",
  "source": "..."
}
"""

In [50]:
revision_input = f"""
ORIGINAL ARTICLE

Title:
{winner["title"]}

Published:
{winner["published"]}

Summary:
{winner["summary"]}

Source:
{winner["url"]}


DRAFT INSTAGRAM CONTENT

{json.dumps(generation_result, ensure_ascii=False, indent=2)}


FACT-CHECKING REPORT

{json.dumps(json.loads(qa_response.text.strip('```json').strip('```')), ensure_ascii=False, indent=2)}
"""

In [51]:
revision_response = client.models.generate_content(
    model="gemini-3.6-flash",
    contents=revision_prompt + "\n\n" + revision_input
)

print(revision_response.text)

{
  "carousel": [
    {
      "slide": 1,
      "headline": "Bunga KPR Stabil, Tapi Kok Pada Ngerem Beli Rumah?",
      "body": "Suku bunga KPR tercatat stabil di angka 6,77%. Tapi uniknya, tren beli rumah dan refinancing justru lagi melambat. Yuk, kita bedah artinya buat rencana hunian pertama kamu!"
    },
    {
      "slide": 2,
      "headline": "Apa yang Sebenarnya Terjadi?",
      "body": "Berdasarkan data pasar terbaru, tingkat suku bunga KPR berada di posisi stabil. Momen ini diwarnai dengan penurunan kecepatan atau perlambatan pada permintaan pembelian rumah baru serta pengajuan refinancing KPR."
    },
    {
      "slide": 3,
      "headline": "Angka Kuncinya: 6,77%",
      "body": "Angka 6,77% ini mencerminkan rata-rata tingkat suku bunga KPR yang terpantau stabil saat ini. Kondisi ini bisa jadi gambaran awal buat kamu yang lagi mulai riset pasar hunian."
    },
    {
      "slide": 4,
      "headline": "Dampaknya ke Pasar Properti",
      "body": "Ketika suku bunga stabil tetapi permintaan beli dan refinancing melambat, ini menandakan pasar sedang dalam fase kehati-hatian. Banyak calon pembeli yang memilih untuk wait and see sebelum mengambil keputusan finansial besar."
    },
    {
      "slide": 5,
      "headline": "Artinya Buat Kamu yang Mau Beli Rumah",
      "body": "Pasar yang sedang melambat memberi kamu napas ekstra untuk tidak terburu-buru. Suku bunga yang stabil di 6,77% memudahkan kamu dalam merancang estimasi cicilan berdasarkan kondisi pasar saat ini."
    },
    {
      "slide": 6,
      "headline": "Langkah Finansial Cerdas",
      "body": "(Catatan: Ini panduan finansial umum, bukan nasihat pribadi). Momen pasar melambat cocok dipakai untuk merapikan cash flow dan menabung DP. Idealnya, alokasikan total cicilan utang maksimal 30% dari gaji bulananmu."
    },
    {
      "slide": 7,
      "headline": "Siap Rencanakan Rumah Impian?",
      "body": "Bunga KPR stabil 6,77% adalah kesempatan bagus buat makin melek finansial. Pelajari pasarnya, hitung simulasinya, dan ambil langkah saat kamu benar-benar siap secara finansial!"
    }
  ],
  "caption": "Lagi mikir-mikir mau ambil KPR atau tunda dulu? 🏡\n\nKabar terbaru menunjukkan kalau suku bunga KPR saat ini berada di posisi stabil yaitu 6,77%. Uniknya, di tengah suku bunga yang stabil ini, minat masyarakat untuk membeli rumah baru maupun melakukan refinancing KPR justru tercatat mengalami perlambatan.\n\nBuat kamu Gen Z dan millennial yang sedang merencanakan rumah pertama, situasi pasar ini bisa jadi momen pas untuk bernapas sejenak dan merapikan kondisi keuangan. Suku bunga yang stabil memudahkan kamu dalam merancang simulasi cicilan berdasarkan kondisi pasar saat ini.\n\nIngat, pastikan kondisi finansialmu sudah benar-benar siap sebelum berkomitmen pada KPR jangka panjang, ya!\n\nSave postingan ini buat pengingat finansialmu dan share ke teman kamu yang lagi berburu rumah! 💡",
  "cta": "Ketik 'KPR' di kolom komentar kalau kamu mau mulai simulasi cicilan rumah impianmu hari ini!",
  "source": "Pluang (Rabu, 19 Agustus 2026)"
}

In [52]:
final_draft = json.loads(revision_response.text.strip('```json').strip('```'))

final_qa_input = f"""
ORIGINAL NEWS ARTICLE

Title:
{winner["title"]}

Published:
{winner["published"]}

Summary:
{winner["summary"]}

Source:
{winner["url"]}


REVISED INSTAGRAM CONTENT

{json.dumps(final_draft, ensure_ascii=False, indent=2)}
"""

final_qa_response = client.models.generate_content(
    model="gemini-3.6-flash",
    contents=qa_prompt + "\n\n" + final_qa_input
)

print(final_qa_response.text)

```json
{
  "overall_status": "NEEDS_REVISION",
  "issues": [
    {
      "slide": 3,
      "problematic_statement": "Angka 6,77% ini mencerminkan rata-rata tingkat suku bunga KPR yang terpantau stabil saat ini.",
      "reason": "Sumber asli hanya menyatakan 'Suku bunga KPR stabil di 6,77%' dan tidak secara eksplisit menyebutkan bahwa angka tersebut merupakan 'rata-rata'. Menambahkan kata 'rata-rata' mengasumsikan metodologi statistik yang tidak disebutkan dalam sumber.",
      "severity": "LOW",
      "suggested_correction": "Angka 6,77% ini mencerminkan tingkat suku bunga KPR yang terpantau stabil saat ini."
    }
  ]
}
```

In [53]:
final_content = generation_result.copy()

In [54]:
final_content = json.loads(revision_response.text)

In [55]:
print(json.dumps(final_content, ensure_ascii=False, indent=2))

{
  "carousel": [
    {
      "slide": 1,
      "headline": "Bunga KPR Stabil, Tapi Kok Pada Ngerem Beli Rumah?",
      "body": "Suku bunga KPR tercatat stabil di angka 6,77%. Tapi uniknya, tren beli rumah dan refinancing justru lagi melambat. Yuk, kita bedah artinya buat rencana hunian pertama kamu!"
    },
    {
      "slide": 2,
      "headline": "Apa yang Sebenarnya Terjadi?",
      "body": "Berdasarkan data pasar terbaru, tingkat suku bunga KPR berada di posisi stabil. Momen ini diwarnai dengan penurunan kecepatan atau perlambatan pada permintaan pembelian rumah baru serta pengajuan refinancing KPR."
    },
    {
      "slide": 3,
      "headline": "Angka Kuncinya: 6,77%",
      "body": "Angka 6,77% ini mencerminkan rata-rata tingkat suku bunga KPR yang terpantau stabil saat ini. Kondisi ini bisa jadi gambaran awal buat kamu yang lagi mulai riset pasar hunian."
    },
    {
      "slide": 4,
      "headline": "Dampaknya ke Pasar Properti",
      "body": "Ketika suku bunga stabil tetapi permintaan beli dan refinancing melambat, ini menandakan pasar sedang dalam fase kehati-hatian. Banyak calon pembeli yang memilih untuk wait and see sebelum mengambil keputusan finansial besar."
    },
    {
      "slide": 5,
      "headline": "Artinya Buat Kamu yang Mau Beli Rumah",
      "body": "Pasar yang sedang melambat memberi kamu napas ekstra untuk tidak terburu-buru. Suku bunga yang stabil di 6,77% memudahkan kamu dalam merancang estimasi cicilan berdasarkan kondisi pasar saat ini."
    },
    {
      "slide": 6,
      "headline": "Langkah Finansial Cerdas",
      "body": "(Catatan: Ini panduan finansial umum, bukan nasihat pribadi). Momen pasar melambat cocok dipakai untuk merapikan cash flow dan menabung DP. Idealnya, alokasikan total cicilan utang maksimal 30% dari gaji bulananmu."
    },
    {
      "slide": 7,
      "headline": "Siap Rencanakan Rumah Impian?",
      "body": "Bunga KPR stabil 6,77% adalah kesempatan bagus buat makin melek finansial. Pelajari pasarnya, hitung simulasinya, dan ambil langkah saat kamu benar-benar siap secara finansial!"
    }
  ],
  "caption": "Lagi mikir-mikir mau ambil KPR atau tunda dulu? 🏡\n\nKabar terbaru menunjukkan kalau suku bunga KPR saat ini berada di posisi stabil yaitu 6,77%. Uniknya, di tengah suku bunga yang stabil ini, minat masyarakat untuk membeli rumah baru maupun melakukan refinancing KPR justru tercatat mengalami perlambatan.\n\nBuat kamu Gen Z dan millennial yang sedang merencanakan rumah pertama, situasi pasar ini bisa jadi momen pas untuk bernapas sejenak dan merapikan kondisi keuangan. Suku bunga yang stabil memudahkan kamu dalam merancang simulasi cicilan berdasarkan kondisi pasar saat ini.\n\nIngat, pastikan kondisi finansialmu sudah benar-benar siap sebelum berkomitmen pada KPR jangka panjang, ya!\n\nSave postingan ini buat pengingat finansialmu dan share ke teman kamu yang lagi berburu rumah! 💡",
  "cta": "Ketik 'KPR' di kolom komentar kalau kamu mau mulai simulasi cicilan rumah impianmu hari ini!",
  "source": "Pluang (Rabu, 19 Agustus 2026)"
}

In [56]:
final_content["carousel"][2]["body"] = (
    "Angka 6,77% ini mencerminkan tingkat suku bunga KPR "
    "yang terpantau stabil saat ini."
)

In [57]:
print(json.dumps(final_content, ensure_ascii=False, indent=2))

{
  "carousel": [
    {
      "slide": 1,
      "headline": "Bunga KPR Stabil, Tapi Kok Pada Ngerem Beli Rumah?",
      "body": "Suku bunga KPR tercatat stabil di angka 6,77%. Tapi uniknya, tren beli rumah dan refinancing justru lagi melambat. Yuk, kita bedah artinya buat rencana hunian pertama kamu!"
    },
    {
      "slide": 2,
      "headline": "Apa yang Sebenarnya Terjadi?",
      "body": "Berdasarkan data pasar terbaru, tingkat suku bunga KPR berada di posisi stabil. Momen ini diwarnai dengan penurunan kecepatan atau perlambatan pada permintaan pembelian rumah baru serta pengajuan refinancing KPR."
    },
    {
      "slide": 3,
      "headline": "Angka Kuncinya: 6,77%",
      "body": "Angka 6,77% ini mencerminkan tingkat suku bunga KPR yang terpantau stabil saat ini."
    },
    {
      "slide": 4,
      "headline": "Dampaknya ke Pasar Properti",
      "body": "Ketika suku bunga stabil tetapi permintaan beli dan refinancing melambat, ini menandakan pasar sedang dalam fase kehati-hatian. Banyak calon pembeli yang memilih untuk wait and see sebelum mengambil keputusan finansial besar."
    },
    {
      "slide": 5,
      "headline": "Artinya Buat Kamu yang Mau Beli Rumah",
      "body": "Pasar yang sedang melambat memberi kamu napas ekstra untuk tidak terburu-buru. Suku bunga yang stabil di 6,77% memudahkan kamu dalam merancang estimasi cicilan berdasarkan kondisi pasar saat ini."
    },
    {
      "slide": 6,
      "headline": "Langkah Finansial Cerdas",
      "body": "(Catatan: Ini panduan finansial umum, bukan nasihat pribadi). Momen pasar melambat cocok dipakai untuk merapikan cash flow dan menabung DP. Idealnya, alokasikan total cicilan utang maksimal 30% dari gaji bulananmu."
    },
    {
      "slide": 7,
      "headline": "Siap Rencanakan Rumah Impian?",
      "body": "Bunga KPR stabil 6,77% adalah kesempatan bagus buat makin melek finansial. Pelajari pasarnya, hitung simulasinya, dan ambil langkah saat kamu benar-benar siap secara finansial!"
    }
  ],
  "caption": "Lagi mikir-mikir mau ambil KPR atau tunda dulu? 🏡\n\nKabar terbaru menunjukkan kalau suku bunga KPR saat ini berada di posisi stabil yaitu 6,77%. Uniknya, di tengah suku bunga yang stabil ini, minat masyarakat untuk membeli rumah baru maupun melakukan refinancing KPR justru tercatat mengalami perlambatan.\n\nBuat kamu Gen Z dan millennial yang sedang merencanakan rumah pertama, situasi pasar ini bisa jadi momen pas untuk bernapas sejenak dan merapikan kondisi keuangan. Suku bunga yang stabil memudahkan kamu dalam merancang simulasi cicilan berdasarkan kondisi pasar saat ini.\n\nIngat, pastikan kondisi finansialmu sudah benar-benar siap sebelum berkomitmen pada KPR jangka panjang, ya!\n\nSave postingan ini buat pengingat finansialmu dan share ke teman kamu yang lagi berburu rumah! 💡",
  "cta": "Ketik 'KPR' di kolom komentar kalau kamu mau mulai simulasi cicilan rumah impianmu hari ini!",
  "source": "Pluang (Rabu, 19 Agustus 2026)"
}

In [58]:
import json

sample_news = candidate_df[
    ["title", "url", "published", "summary", "query"]
].to_dict(orient="records")

with open("sample_news.json", "w", encoding="utf-8") as f:
    json.dump(sample_news, f, ensure_ascii=False, indent=2)